//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SazonovaDR304
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int MarkNum { get; set; }
        public int IdStudent { get; set; }
        public int Mark { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int Subject { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
