//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SazonovaDR304
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class kvalEkzSazonova304Entities : DbContext
    {
        public kvalEkzSazonova304Entities()
            : base("name=kvalEkzSazonova304Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<ReportingType> ReportingType { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<viewMarks_Result> viewMarks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewMarks_Result>("viewMarks");
        }
    
        public virtual ObjectResult<viewSubjects_Result> viewSubjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewSubjects_Result>("viewSubjects");
        }
    
        public virtual ObjectResult<viewSearchStudents_Result> viewSearchStudents(string seachString)
        {
            var seachStringParameter = seachString != null ?
                new ObjectParameter("seachString", seachString) :
                new ObjectParameter("seachString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewSearchStudents_Result>("viewSearchStudents", seachStringParameter);
        }
    
        public virtual ObjectResult<viewSearchMarks_Result> viewSearchMarks(string seachString)
        {
            var seachStringParameter = seachString != null ?
                new ObjectParameter("seachString", seachString) :
                new ObjectParameter("seachString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewSearchMarks_Result>("viewSearchMarks", seachStringParameter);
        }
    
        public virtual ObjectResult<viewSearcSubjects_Result> viewSearcSubjects(string seachString)
        {
            var seachStringParameter = seachString != null ?
                new ObjectParameter("seachString", seachString) :
                new ObjectParameter("seachString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewSearcSubjects_Result>("viewSearcSubjects", seachStringParameter);
        }
    }
}
